Repository boongObbang-plz/boongObbang, pull requests merged in 2023-11, with the labels that each got.

#4 chore: docker 환경 구축
  .gitignore
  backend/Dockerfile
  backend/build.gradle
  docker-compose.yml
  frontend/Dockerfile
  mariadb/Dockerfile
  mariadb/db_start.sh
Labels: 배포📮

#9 update: letter images 변경
  frontend/src/images/letter_choco.png
  frontend/src/images/letter_cream.png
  frontend/src/images/letter_mint.png
  frontend/src/images/letter_pizza.png
  frontend/src/images/letter_redbean.png
  frontend/src/images/letter_sweetpotato.png
Labels: 스타일👗, FrontEnd💛

#10 feat: spring security와 oauth2, jwt 적용
  backend/build.gradle
  backend/src/main/java/com/example/boongObbang/config/BCryptConfig.java
  backend/src/main/java/com/example/boongObbang/config/RedisConfig.java
  backend/src/main/java/com/example/boongObbang/config/SecurityConfig.java
  backend/src/main/java/com/example/boongObbang/dto/TokenDto.java
  backend/src/main/java/com/example/boongObbang/entity/Token.java
  backend/src/main/java/com/example/boongObbang/entity/User.java
  backend/src/main/java/com/example/boongObbang/jwt/JwtProvider.java
  backend/src/main/java/com/example/boongObbang/oauth2/CustomOAuth2UserService.java
  backend/src/main/java/com/example/boongObbang/oauth2/OAuth2Attribute.java
  backend/src/main/java/com/example/boongObbang/oauth2/OAuth2FailureHandler.java
  backend/src/main/java/com/example/boongObbang/oauth2/OAuth2SuccessHandler.java
  backend/src/main/java/com/example/boongObbang/repository/TokenRedisRepository.java
  backend/src/main/java/com/example/boongObbang/repository/UserRepository.java
  backend/src/main/java/com/example/boongObbang/response/CustomResponse.java
  backend/src/test/java/com/example/boongObbang/repository/UserRepositoryTest.java
Labels: 기능 추가🌸, BackEnd💙

#11 feat: JwtAuthorizationFilter 적용
  backend/src/main/java/com/example/boongObbang/config/SecurityConfig.java
  backend/src/main/java/com/example/boongObbang/jwt/JwtAuthorizationFilter.java
  backend/src/main/java/com/example/boongObbang/jwt/JwtProvider.java
  backend/src/main/java/com/example/boongObbang/oauth2/OAuth2SuccessHandler.java
Labels: 기능 추가🌸, BackEnd💙

#15 feat: default screen 적용
  .gitignore
  docker-compose.yml
  frontend/Dockerfile
  frontend/jsconfig.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/components/MainPage/Bottom.js
  frontend/src/components/MainPage/DDay.js
  frontend/src/components/MainPage/DefaultScreen.js
  frontend/src/components/MainPage/Display.js
  frontend/src/components/MainPage/Grill.js
  frontend/src/components/MainPage/Letter.js
  frontend/src/components/MainPage/Letters.js
  frontend/src/components/MainPage/Light.js
  frontend/src/components/MainPage/LightBulb.js
  frontend/src/components/MainPage/LightBulbs.js
  frontend/src/components/MainPage/Roof.js
  frontend/src/components/MainPage/Title.js
  frontend/src/components/MainPage/Top.js
  frontend/src/components/MainPage/fake_api_data.json
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/pages/MainPage.js
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
  frontend/tailwind.config.js
Labels: 기능 추가🌸, FrontEnd💛

#16 fix: 삭제된 docker file 복구
  docker-compose.yml
  frontend/.gitignore
  frontend/Dockerfile
Labels: 스타일👗

#19 fix: spring security를 사용한 oauth2에서 rest api를 사용한 oauth2로 구성
  backend/src/main/java/com/example/boongObbang/config/SecurityConfig.java
  backend/src/main/java/com/example/boongObbang/controller/UserController.java
  backend/src/main/java/com/example/boongObbang/dto/GoogleDto.java
  backend/src/main/java/com/example/boongObbang/dto/GoogleProfileDto.java
  backend/src/main/java/com/example/boongObbang/dto/KakaoDto.java
  backend/src/main/java/com/example/boongObbang/dto/KakaoProfileDto.java
  backend/src/main/java/com/example/boongObbang/dto/LoginRequestDto.java
  backend/src/main/java/com/example/boongObbang/dto/LoginResponseDto.java
  backend/src/main/java/com/example/boongObbang/dto/LoginServiceDto.java
  backend/src/main/java/com/example/boongObbang/jwt/JwtAuthorizationFilter.java
  backend/src/main/java/com/example/boongObbang/jwt/JwtProvider.java
  backend/src/main/java/com/example/boongObbang/oauth2/CustomOAuth2UserService.java
  backend/src/main/java/com/example/boongObbang/oauth2/OAuth2Attribute.java
  backend/src/main/java/com/example/boongObbang/oauth2/OAuth2FailureHandler.java
  backend/src/main/java/com/example/boongObbang/oauth2/OAuth2SuccessHandler.java
  backend/src/main/java/com/example/boongObbang/service/UserService.java
Labels: 버그🐞, BackEnd💙

#25 fix: controller 테스트시 403이 뜨는 오류 해결
  backend/src/main/java/com/example/boongObbang/config/SecurityConfig.java
  backend/src/main/java/com/example/boongObbang/controller/UserController.java
  backend/src/main/java/com/example/boongObbang/dto/CreateSettingRequestDto.java
  backend/src/main/java/com/example/boongObbang/jwt/JwtAuthorizationFilter.java
  backend/src/test/java/com/example/boongObbang/controller/SettingControllerTest.java
Labels: 버그🐞, BackEnd💙

#28 feat: 마차 수정하기 구현
  backend/src/main/java/com/example/boongObbang/controller/SettingController.java
  backend/src/main/java/com/example/boongObbang/dto/PatchSettingRequestDto.java
  backend/src/main/java/com/example/boongObbang/exception/CustomExceptionHandler.java
  backend/src/main/java/com/example/boongObbang/exception/exceptions/NoExistSettingException.java
  backend/src/main/java/com/example/boongObbang/response/ResponseMessage.java
  backend/src/main/java/com/example/boongObbang/service/SettingService.java
  backend/src/test/java/com/example/boongObbang/controller/SettingControllerTest.java
  backend/src/test/java/com/example/boongObbang/service/SettingServiceTest.java
Labels: 기능 추가🌸, BackEnd💙

#31 feat: 마차 삭제하기 구현
  backend/src/main/java/com/example/boongObbang/controller/SettingController.java
  backend/src/main/java/com/example/boongObbang/service/SettingService.java
  backend/src/test/java/com/example/boongObbang/controller/SettingControllerTest.java
  backend/src/test/java/com/example/boongObbang/service/SettingServiceTest.java
Labels: 기능 추가🌸, BackEnd💙

#27 feat: 남의 메인페이지 구현
  frontend/package-lock.json
  frontend/public/images/icon_before.png
  frontend/src/components/LoginPage/Bottom.jsx
  frontend/src/components/LoginPage/NoticeButton.jsx
  frontend/src/components/MainPage/Bottom.jsx
  frontend/src/components/MainPage/DDay.jsx
  frontend/src/components/MainPage/Display.jsx
  frontend/src/components/MainPage/Grill.jsx
  frontend/src/components/MainPage/Letter.jsx
  frontend/src/components/MainPage/Light.jsx
  frontend/src/components/MainPage/Roof.jsx
  frontend/src/components/MainPage/Title.jsx
  frontend/src/components/NotMyMainPage/BOB.jsx
  frontend/src/components/NotMyMainPage/Bottom.jsx
  frontend/src/components/NotMyMainPage/MakeLetter.jsx
  frontend/src/components/NotMyMainPage/MakeLetter/BOB.jsx
  frontend/src/components/NotMyMainPage/MakeLetter/ChooseBOB.jsx
  frontend/src/components/NotMyMainPage/MakeLetter/FinalCheckSubmit.jsx
  frontend/src/components/NotMyMainPage/MakeLetter/MakeLetter.jsx
  frontend/src/components/NotMyMainPage/MakeLetter/TopOfChooseBOB.jsx
  frontend/src/components/NotMyMainPage/MakeLetter/TopOfWriteLetter.jsx
  frontend/src/components/NotMyMainPage/MakeLetter/WriteLetter.jsx
  frontend/src/components/NotMyMainPage/MakeLetterBTN.jsx
  frontend/src/components/NotMyMainPage/NextCloseBTN.jsx
  frontend/src/components/layout.jsx
  frontend/src/images/kakao_login.png
  frontend/src/pages/NotMyMainPage.jsx
  frontend/src/states/ModalState.js
  frontend/tailwind.config.js
Labels: 기능 추가🌸, FrontEnd💛

#33 feat: logout 구현
  backend/src/main/java/com/example/boongObbang/config/SecurityConfig.java
  backend/src/main/java/com/example/boongObbang/controller/SettingController.java
  backend/src/main/java/com/example/boongObbang/jwt/JwtProvider.java
  backend/src/main/java/com/example/boongObbang/service/SettingService.java
Labels: 버그🐞, 기능 추가🌸, BackEnd💙

#35 feat: 나의 메인페이지 조회 구현
  backend/src/main/java/com/example/boongObbang/config/SecurityConfig.java
  backend/src/main/java/com/example/boongObbang/controller/MainPageController.java
  backend/src/main/java/com/example/boongObbang/dto/MainPageResponseDto.java
  backend/src/main/java/com/example/boongObbang/dto/MessageDto.java
  backend/src/main/java/com/example/boongObbang/entity/Message.java
  backend/src/main/java/com/example/boongObbang/repository/MessageRepository.java
  backend/src/main/java/com/example/boongObbang/service/MainPageService.java
  backend/src/test/java/com/example/boongObbang/controller/MainPageControllerTest.java
  backend/src/test/java/com/example/boongObbang/repository/MessageRepositoryTest.java
  backend/src/test/java/com/example/boongObbang/service/MainPageServiceTest.java
Labels: 기능 추가🌸, BackEnd💙

#37 feat: 링크 공유하기 구현
  backend/src/main/java/com/example/boongObbang/controller/MainPageController.java
  backend/src/main/java/com/example/boongObbang/dto/LinkResponseDto.java
  backend/src/main/java/com/example/boongObbang/service/MainPageService.java
  backend/src/test/java/com/example/boongObbang/controller/MainPageControllerTest.java
  backend/src/test/java/com/example/boongObbang/service/MainPageServiceTest.java
Labels: 기능 추가🌸, BackEnd💙

#40 feat: 12월 25일이후 편지작성 제어 적용
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/NotMyMainPage/Bottom.jsx
  frontend/src/components/NotMyMainPage/MakeLetterBTN.jsx
Labels: 기능 추가🌸, FrontEnd💛

#45 feat: 남의 페이지 조회 구현
  backend/src/main/java/com/example/boongObbang/config/SecurityConfig.java
  backend/src/main/java/com/example/boongObbang/controller/OtherMainPageController.java
  backend/src/main/java/com/example/boongObbang/exception/CustomExceptionHandler.java
  backend/src/main/java/com/example/boongObbang/exception/exceptions/UrlErrorException.java
  backend/src/main/java/com/example/boongObbang/jwt/JwtAuthorizationFilter.java
  backend/src/main/java/com/example/boongObbang/response/ResponseMessage.java
  backend/src/main/java/com/example/boongObbang/service/MainPageService.java
  backend/src/test/java/com/example/boongObbang/controller/MainPageControllerTest.java
  backend/src/test/java/com/example/boongObbang/service/MainPageServiceTest.java
Labels: 기능 추가🌸, BackEnd💙

#49 chore: git action yml파일 추가
  .github/workflows/main.yml
Labels: 배포📮

#51 chore: git action yml파일에서 spring main/resources 폴더 추가
  .github/workflows/main.yml
Labels: 배포📮

#52 chore: git action yml파일에서 잘못된 문법 수정
  .github/workflows/main.yml
Labels: 배포📮

#53 chore: git action yml 파일에서 ec2에 도커 이미지 pull 구현
  .github/workflows/main.yml
Labels: 배포📮

#54 chore: git action yml 파일에서 run을 script로 변경
  .github/workflows/main.yml
Labels: 배포📮

#55 chore: git action yml 파일에서 script 위치 변경
  .github/workflows/main.yml
Labels: 배포📮

#56 chore: git action yml 파일에서 docker build 문법오류 수정
  .github/workflows/main.yml
Labels: 배포📮

#57 chore: git action yml 파일에서 docker를 docker-compose로 변경
  .github/workflows/main.yml
Labels: 배포📮

#58 chore: git action yml 파일에서 ssh uses 변경
  .github/workflows/main.yml
Labels: 배포📮

#59 chore: git action yml 파일에서 ssh 버전 변경
  .github/workflows/main.yml
Labels: 배포📮

#60 chore: git action yml 파일에서 docker 이미지와 컨테이너 삭제 스크립트 실행문 추가
  .github/workflows/main.yml
Labels: 배포📮

#61 chore: docker hub에 docker-compose push 오류 해결
  .github/workflows/main.yml
  docker-compose.yml
Labels: 배포📮

#62 chore: backend 테스트 시 오류 발생하여, 잠시 주석 처리
  .github/workflows/main.yml
  docker-compose.yml
Labels: 배포📮

#64 chore: main에 push될 시 AWS S3로 파일 옮기는 github action yml파일 작성
  .github/workflows/main.yml
Labels: 배포📮

#65 chore: github action에서 AWS S3로 이동 명령어 수정
  .github/workflows/main.yml
Labels: 배포📮

#66 chore: AWS S3에 업로드 명령어 수정
  .github/workflows/main.yml
Labels: 배포📮

#67 chore: S3에 zip 형식으로 업로드 수정 및 codedeploy 추가
  .github/workflows/main.yml
Labels: 배포📮

#68 chore: S3에 zip 형식으로 업로드 경로 문제 수정
  .github/workflows/main.yml
Labels: 배포📮

#69 chore: S3에 zip 형식으로 업로드 경로 에러 수정
  .github/workflows/main.yml
Labels: 배포📮

#70 chore: S3에 zip 형식으로 업로드 형식 수정
  .github/workflows/main.yml
Labels: 배포📮

#71 chore: S3에 업로드 시 옵션 제거
  .github/workflows/main.yml
Labels: 배포📮

#72 chore: code deploy 실행 시 경로 수정
  .github/workflows/main.yml
Labels: 배포📮

#73 chore: aws default region 추가
  .github/workflows/main.yml
Labels: 배포📮

#74 chore:ubuntu 버전 변경
  .github/workflows/main.yml
Labels: 배포📮

#75 chore: code deploy 명령어 실행시 region 추가
  .github/workflows/main.yml
Labels: 배포📮

#76 chore: env region 다시 설정
  .github/workflows/main.yml
Labels: 배포📮

#77 chore: configure aws credentials 추가
  .github/workflows/main.yml
Labels: 배포📮

#78 chore: code deploy에서 사용할 appspec.yml과 deploy.sh 생성
  appspec.yml
  script/deploy.sh
Labels: 배포📮

#79 chore: appspec.yml의 owner와 group 수정
  appspec.yml
Labels: 배포📮

#80 chore: 오타 수정 및 경로 재설정
  .github/workflows/main.yml
  script/deploy.sh
Labels: 배포📮

#83 feat: 모달 반응형 적용
  frontend/src/components/LoginPage/Bottom.jsx
  frontend/src/components/LoginPage/CloseButton.jsx
  frontend/src/components/LoginPage/Message.jsx
  frontend/src/components/LoginPage/MessageTitle.jsx
  frontend/src/components/LoginPage/Notice.jsx
  frontend/src/components/LoginPage/Title.jsx
  frontend/src/components/MainPage/DDay.jsx
  frontend/src/components/MainPage/Display.jsx
  frontend/src/components/MainPage/Light.jsx
  frontend/src/components/MainPage/Roof.jsx
  frontend/src/components/MainPage/Title.jsx
  frontend/src/components/MainPage/Top.jsx
  frontend/src/components/MainPage/readLetter/FinalCheckDelete.jsx
  frontend/src/components/MainPage/readLetter/LetterPop.jsx
  frontend/src/components/MainPage/readLetter/LetterPopButtons.jsx
  frontend/src/components/MainPage/readLetter/LetterPopTextArea.jsx
  frontend/src/components/NotMyMainPage/Bottom.jsx
  frontend/src/components/NotMyMainPage/MakeLetter/BOB.jsx
  frontend/src/components/NotMyMainPage/MakeLetter/ChooseBOB.jsx
  frontend/src/components/NotMyMainPage/MakeLetter/FinalCheckSubmit.jsx
  frontend/src/components/NotMyMainPage/MakeLetter/MakeLetter.jsx
  frontend/src/components/NotMyMainPage/MakeLetter/TopOfChooseBOB.jsx
  frontend/src/components/NotMyMainPage/MakeLetter/TopOfWriteLetter.jsx
  frontend/src/components/NotMyMainPage/MakeLetter/WriteLetter.jsx
  frontend/src/components/NotMyMainPage/Notice.jsx
  frontend/src/components/NotMyMainPage/NoticeBTN.jsx
  frontend/src/components/SettingPage/Header.jsx
  frontend/src/components/SettingPage/Label.jsx
  frontend/src/components/SettingPage/Name.jsx
  frontend/src/components/SettingPage/PreView.jsx
  frontend/src/components/SettingPage/StartButton.jsx
  frontend/src/components/layout.jsx
  frontend/src/index.css
  frontend/src/pages/MainPage.jsx
  frontend/src/pages/NotMyMainPage.jsx
Labels: 기능 추가🌸, FrontEnd💛, 리팩토링⚙️

#81 Feat/pre setting page
  frontend/Dockerfile
  frontend/package.json
  frontend/public/images/google_symbol.png
  frontend/public/images/kakao_login.png
  frontend/public/images/kakao_symbol.png
  frontend/src/App.jsx
  frontend/src/components/LoginPage/Board.jsx
  frontend/src/components/LoginPage/CloseButton.jsx
  frontend/src/components/LoginPage/GoogleLoginButton.jsx
  frontend/src/components/LoginPage/KakaoRedirect.jsx
  frontend/src/components/LoginPage/Roof.jsx
  frontend/src/components/LoginPage/SocialKakao.jsx
  frontend/src/components/LoginPage/Title.jsx
  frontend/src/components/MainPage/SettingButton.jsx
  frontend/src/components/MainPage/ShareButton.jsx
  frontend/src/components/MainPage/readLetter/DeleteButton.jsx
  frontend/src/components/NotMyMainPage/MakeLetter/FinalCheckSubmit.jsx
  frontend/src/components/NotMyMainPage/MakeLetter/TopOfWriteLetter.jsx
  frontend/src/components/SettingPage/ChooseLight.jsx
  frontend/src/components/SettingPage/ChooseRoof.jsx
  frontend/src/components/SettingPage/CloseBTN.jsx
  frontend/src/components/SettingPage/DefaultScreen.jsx
  frontend/src/components/SettingPage/DeleteIdBTN.jsx
  frontend/src/components/SettingPage/FinalCheckDeleteId.jsx
  frontend/src/components/SettingPage/FinalCheckLogout.jsx
  frontend/src/components/SettingPage/Header.jsx
  frontend/src/components/SettingPage/Label.jsx
  frontend/src/components/SettingPage/Light.jsx
  frontend/src/components/SettingPage/LogoutBTN.jsx
  frontend/src/components/SettingPage/Name.jsx
  frontend/src/components/SettingPage/PreView.jsx
  frontend/src/components/SettingPage/QnABTN.jsx
  frontend/src/components/SettingPage/Roof.jsx
  frontend/src/components/SettingPage/StartButton.jsx
  frontend/src/components/layout.jsx
  frontend/src/pages/LoginPage.jsx
  frontend/src/pages/PreSettingPage.jsx
  frontend/src/states/ModalState.js
Labels: 기능 추가🌸, FrontEnd💛

#48 feat: 편지 쓰기 구현
  backend/src/main/java/com/example/boongObbang/controller/OtherMainPageController.java
  backend/src/main/java/com/example/boongObbang/dto/WriteMessageResponseDto.java
  backend/src/main/java/com/example/boongObbang/service/MainPageService.java
  backend/src/test/java/com/example/boongObbang/controller/MainPageControllerTest.java
  backend/src/test/java/com/example/boongObbang/service/MainPageServiceTest.java
Labels: 기능 추가🌸, BackEnd💙

#86 feat: api 추가
  frontend/src/components/LoginPage/KakaoRedirect.jsx
  frontend/src/components/MainPage/DefaultScreen.jsx
  frontend/src/components/MainPage/ShareButton.jsx
  frontend/src/components/SettingPage/DefaultScreen.jsx
  frontend/src/components/SettingPage/FinalCheckDeleteId.jsx
  frontend/src/components/SettingPage/FinalCheckLogout.jsx
  frontend/src/components/SettingPage/StartButton.jsx
  frontend/src/main.jsx
  frontend/src/states/ModalState.js
Labels: 기능 추가🌸, 테스트✅, FrontEnd💛

#87 fix: 모달 스타일 맞춤 & 반응형 조정
  frontend/src/components/MainPage/Light.jsx
  frontend/src/components/MainPage/readLetter/CloseButton.jsx
  frontend/src/components/MainPage/readLetter/DeleteButton.jsx
  frontend/src/components/MainPage/readLetter/LetterPop.jsx
  frontend/src/components/MainPage/readLetter/LetterPopLabel.jsx
  frontend/src/components/MainPage/readLetter/LetterPopTextArea.jsx
  frontend/src/components/NotMyMainPage/MakeLetter/TopOfChooseBOB.jsx
  frontend/src/components/NotMyMainPage/MakeLetter/TopOfWriteLetter.jsx
  frontend/src/components/NotMyMainPage/MakeLetter/WriteLetter.jsx
  frontend/src/components/SettingPage/FinalCheckDeleteId.jsx
  frontend/src/components/SettingPage/FinalCheckLogout.jsx
  frontend/src/components/layout.jsx
  frontend/src/pages/NotMyMainPage.jsx
Labels: FrontEnd💛, 리팩토링⚙️

#85 fix: cors 오류 해결
  backend/src/main/java/com/example/boongObbang/config/SecurityConfig.java
  backend/src/main/java/com/example/boongObbang/controller/UserController.java
  backend/src/main/java/com/example/boongObbang/jwt/JwtAuthorizationFilter.java
  backend/src/main/java/com/example/boongObbang/jwt/JwtProvider.java
Labels: 버그🐞, BackEnd💙

#90 feat: 남의 메인페이지, 편지읽기 & 삭제 API 연결
  docker-compose.yml
  frontend/src/App.jsx
  frontend/src/components/LoginPage/SocialKakao.jsx
  frontend/src/components/MainPage/DefaultScreen.jsx
  frontend/src/components/MainPage/Display.jsx
  frontend/src/components/MainPage/Letter.jsx
  frontend/src/components/MainPage/Letters.jsx
  frontend/src/components/MainPage/readLetter/CloseButton.jsx
  frontend/src/components/MainPage/readLetter/FinalCheckDelete.jsx
  frontend/src/components/MainPage/readLetter/LetterPop.jsx
  frontend/src/components/NotMyMainPage/MakeLetter/FinalCheckSubmit.jsx
  frontend/src/components/NotMyMainPage/MakeLetter/TopOfChooseBOB.jsx
  frontend/src/components/NotMyMainPage/MakeLetter/TopOfWriteLetter.jsx
  frontend/src/components/NotMyMainPage/MakeLetter/WriteLetter.jsx
  frontend/src/components/layout.jsx
  frontend/src/pages/NotMyMainPage.jsx
  frontend/src/states/ModalState.js
Labels: 기능 추가🌸, FrontEnd💛

#88 Style/settings
  frontend/src/App.jsx
  frontend/src/components/LoginPage/Bottom.jsx
  frontend/src/components/LoginPage/GoogleLoginButton.jsx
  frontend/src/components/LoginPage/GoogleRedirect.jsx
  frontend/src/components/LoginPage/NoticeButton.jsx
  frontend/src/components/LoginPage/SocialKakao.jsx
  frontend/src/components/LoginPage/Title.jsx
  frontend/src/components/MainPage/Bottom.jsx
  frontend/src/components/MainPage/DefaultScreen.jsx
  frontend/src/components/MainPage/ShareButton.jsx
  frontend/src/components/SettingPage/DeleteIdBTN.jsx
  frontend/src/components/SettingPage/Name.jsx
  frontend/src/components/SettingPage/QnABTN.jsx
  frontend/src/components/layout.jsx
  frontend/src/pages/MainPage.jsx
  frontend/src/pages/PreSettingPage.jsx
  frontend/src/pages/SettingPage.jsx
Labels: 스타일👗, FrontEnd💛, 리팩토링⚙️

#92 fix: 새로고침 시 토큰 없어지는 문제 조치
  frontend/Dockerfile
  frontend/src/states/ModalState.js
Labels: 버그🐞, FrontEnd💛

#96 fix: API 에러 핸들링 적용
  frontend/src/components/MainPage/ShareButton.jsx
  frontend/src/components/MainPage/readLetter/FinalCheckDelete.jsx
  frontend/src/components/MainPage/readLetter/LetterPop.jsx
  frontend/src/pages/MainPage.jsx
  frontend/src/pages/NotMyMainPage.jsx
Labels: FrontEnd💛, 리팩토링⚙️

#97 Fix/login
  frontend/src/App.jsx
  frontend/src/components/LoginPage/GoogleLoginButton.jsx
  frontend/src/components/LoginPage/KakaoRedirect.jsx
  frontend/src/components/SettingPage/FinalCheckDeleteId.jsx
  frontend/src/components/SettingPage/FinalCheckLogout.jsx
  frontend/src/components/SettingPage/StartButton.jsx
Labels: FrontEnd💛, 리팩토링⚙️

#100 feat: favicon 변경, 로그인창 안내문구 추가, setting 페이지 토큰 검사로직 추가
  frontend/index.html
  frontend/public/images/favicon.png
  frontend/src/pages/LoginPage.jsx
  frontend/src/pages/SettingPage.jsx
Labels: 기능 추가🌸, FrontEnd💛, 리팩토링⚙️

#102 Fix/token
  frontend/src/components/LoginPage/Redirect.jsx
  frontend/src/components/MainPage/Grill.jsx
  frontend/src/components/MainPage/Roof.jsx
  frontend/src/components/SettingPage/StartButton.jsx
  frontend/src/components/layout.jsx
  frontend/src/pages/MainPage.jsx
Labels: 버그🐞, FrontEnd💛

#101 fix: oauth 오류 수정
  backend/src/main/java/com/example/boongObbang/config/SecurityConfig.java
  backend/src/main/java/com/example/boongObbang/dto/GoogleProfileDto.java
  backend/src/main/java/com/example/boongObbang/dto/KakaoProfileDto.java
  backend/src/main/java/com/example/boongObbang/jwt/JwtAuthorizationFilter.java
  backend/src/main/java/com/example/boongObbang/jwt/JwtProvider.java
  backend/src/main/java/com/example/boongObbang/service/MainPageService.java
  backend/src/main/java/com/example/boongObbang/service/UserService.java
  backend/src/test/java/com/example/boongObbang/controller/MainPageControllerTest.java
  backend/src/test/java/com/example/boongObbang/controller/SettingControllerTest.java
Labels: 버그🐞, BackEnd💙

#104 Fix/token
  frontend/src/components/MainPage/Display.jsx
  frontend/src/components/MainPage/ShareButton.jsx
  frontend/src/components/MainPage/readLetter/LetterPop.jsx
  frontend/src/components/SettingPage/FinalCheckDeleteId.jsx
  frontend/src/components/layout.jsx
  frontend/src/pages/NotMyMainPage.jsx
Labels: 버그🐞, 스타일👗, FrontEnd💛

#105 fix: 회원 탈퇴 시 메세지 삭제 수정
  backend/src/main/java/com/example/boongObbang/service/SettingService.java
Labels: 버그🐞, BackEnd💙

#107 Fix/token
  frontend/src/components/LoginPage/Redirect.jsx
  frontend/src/components/SettingPage/FinalCheckDeleteId.jsx
  frontend/src/components/SettingPage/FinalCheckLogout.jsx
  frontend/src/components/SettingPage/StartButton.jsx
  frontend/src/pages/MainPage.jsx
  frontend/src/pages/SettingPage.jsx
Labels: 버그🐞, FrontEnd💛, 리팩토링⚙️
